name: kbb
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.8.4
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.7
  http: ^1.3.0
  google_fonts: ^4.0.3
  provider: ^6.1.4
  flutter_image_compress: ^2.1.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  url_launcher: ^6.1.10
  path_provider: ^2.1.2
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/loading_screen.png